
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb| 
   vb.memory = "1024"
  end
    
  config.vm.provision "docker" do |d|
    d.pull_images "quay.io/coreos/etcd"
    d.run "quay.io/coreos/etcd",
      args: "-p 2379:2379 -p 2380:2380 --restart always -it -d",
      cmd: "/usr/local/bin/etcd --name node --initial-advertise-peer-urls http://0.0.0.0:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379  --initial-cluster node=http://0.0.0.0:2380"
  end 

  config.vm.network "forwarded_port", guest: 2380, host: 2380
  config.vm.network "forwarded_port", guest: 2379, host: 2379
end
